#!/usr/bin/env python3
"""Generate ov-* text-cue + definition-chip compositions for 2026-07-31-sol-vs-fable.
Quiet Register v4 Form 1. Per-video color law: cyan=cut X (Fable), blossom=cut Y (Sol),
amber=shared failure. Neutral cues get a white dot (blossom is reserved = cut Y this video).
All cue copy verbatim / verbatim-tightened from the locked script + anchors.md.
"""
import html as H, os

OUT = "/Users/andydepp/Projects/OperatorOS/agentic-editor/hyperframes-editor/video-projects/2026-07-31-sol-vs-fable/compositions"

CYAN = "#5BA8D8"; BLOSSOM = "#F0A8C2"; AMBER = "#F59E0B"; WHITE = "#e9edf6"; DIM = "#5a6480"

# name, text, dot color, duration, source note
CUES = [
    ("ov-blind-rules",     "FIVE DIMENSIONS · TWENTY-FIVE POINTS · NO LABELS", WHITE,   5.0, "Beat 2 verbatim: 'Five dimensions, twenty-five points, no labels.'"),
    ("ov-slight-pause",    "0:15 — SLIGHT PAUSE",                              CYAN,    5.0, "Clip 1 1:31-3:40 anchor: 'slight pauses at clip heads, 0:15...' (cut X)"),
    ("ov-headroom",        "TOO MUCH HEADROOM AT THE CLIP HEADS",              CYAN,    5.0, "Clip 1 5:08-5:28: 'cut X is leaving too much headroom' + 'clip heads' phrasing from 9:57 anchor (cut X)"),
    ("ov-audio-jumps",     "THE AUDIO JUMPS LEVELS",                           CYAN,    5.0, "Clip 1 10:02: 'Audio jumps level switching from A-roll to screen recording' (cut X)"),
    ("ov-it-fixed-audio",  "IT FIXED THE AUDIO",                               BLOSSOM, 5.0, "Beat 7 / Clip 2 3:11 verbatim (cut Y)"),
    ("ov-repeat-take",     "REPEAT TAKE — 0:39",                               BLOSSOM, 5.0, "Clip 2 2:29: 'At 0:39 we have a repeat take' (cut Y)"),
    ("ov-blind-broke",     "THE BLIND BROKE",                                  WHITE,   5.0, "Beat 8 verbatim: 'So the blind broke.'"),
    ("ov-pacing-flip",     "PAST 5:00 THE PATTERN FLIPS",                      WHITE,   5.0, "Clip 3 9:57: 'flipped from the first five minutes' — comparative finding, neutral"),
    ("ov-both-broll",      "B-ROLL: 1 / 5 · BOTH",                             AMBER,   5.0, "Clip 3 12:39: 'a one. And this is also a one.' — shared failure"),
    ("ov-cheap-qualifier", "CHEAP PER TOKEN IS NOT CHEAP PER JOB",             WHITE,   5.0, "Beat 12 verbatim"),
    ("ov-trial",           "A FOUR VIDEO TRIAL, NOT A CROWN",                  WHITE,   5.0, "Beat 10 verbatim-tightened: 'the winner gets a four video trial, not a crown'"),
    ("ov-system-year",     "THE SYSTEM IS THE THING THAT TOOK ME A YEAR",      WHITE,   5.0, "Beat 13 verbatim. NOTE: overlaps taste-is-the-moat.mov (same line, two-line dim treatment) — editor picks one"),
]

# CTA cue — two lines, brightness hierarchy (line 1 dim, line 2 bright). No blossom
# (blossom = cut Y this video; spending it on the CTA would give it a second meaning).
CTA = ("ov-previous-video",
       "YESTERDAY'S VIDEO IS WHERE THIS WHOLE THING STARTED",
       "GO WATCH THAT ONE NEXT", 6.0,
       "Beat 13 verbatim")

# Definition chips — NEW copy, FLAGGED for Dan voice-gate before final.
CHIPS = [
    ("ov-chip-lufs", "∿", "LUFS",
     "how loud your audio actually feels — the number a leveled mix is tuned to", 6.0),
    ("ov-chip-blind-test", "◎", "BLIND TEST",
     "grading both cuts without knowing which AI made which one", 6.0),
    ("ov-chip-first-pass", "▶", "FIRST PASS",
     "the rough cut the AI hands you before you touch anything", 6.0),
]

HEAD = """<!doctype html>
<!--
  {name} — {note}
  Quiet Register v4 Form 1 text cue. TRANSPARENT canvas -> alpha .mov (ProRes 4444, 29.97).
  Color law (this video): cyan #5BA8D8 = cut X / Fable, blossom #F0A8C2 = cut Y / Sol,
  amber #F59E0B = shared failure, white = neutral. Dot carries the law; text stays white.
  Word-level fade reveal (AIDR reference surface A). No typewriter, no per-character, no scale.
  Generated by gen_overlays.py — edit the generator, not this file.
-->
<html lang="en">
<head>
<meta charset="utf-8" />
<style>
  @font-face {{ font-family:'Geist Mono'; font-weight:400; font-display:block; src:url(assets/fonts/GeistMono-400.woff2) format('woff2'); }}
  @font-face {{ font-family:'Geist Mono'; font-weight:500; font-display:block; src:url(assets/fonts/GeistMono-500.woff2) format('woff2'); }}
  *{{margin:0;padding:0;box-sizing:border-box;}}
  html,body{{width:1920px;height:1080px;overflow:hidden;background:transparent;font-family:'Geist Mono',monospace;}}
  #stage{{position:relative;width:1920px;height:1080px;}}
"""

def word_spans(text, cls="w"):
    out = []
    for tok in text.split(" "):
        if tok in ("·", "—"):
            out.append(f'<span class="{cls} sep">{H.escape(tok)}</span>')
        else:
            out.append(f'<span class="{cls}">{H.escape(tok)}</span>')
    return "\n        ".join(out)

def cue_html(name, text, dot, dur, note):
    return HEAD.format(name=name, note=note) + f"""
  .cue{{position:absolute;left:140px;bottom:300px;display:flex;align-items:baseline;gap:26px;}}
  .dot{{color:{dot};font-size:26px;opacity:0;transform:translateY(-3px);
       text-shadow:0 2px 18px rgba(0,0,0,0.72);}}
  .words{{display:flex;flex-wrap:wrap;gap:0 14px;max-width:1500px;}}
  .w{{font-weight:500;font-size:34px;letter-spacing:0.09em;text-transform:uppercase;color:#e9edf6;
     text-shadow:0 2px 18px rgba(0,0,0,0.72);opacity:0;}}
  .w.sep{{color:{DIM};font-weight:400;}}
</style>
</head>
<body data-hf-duration="{dur}">
  <div id="stage" data-composition-id="main" data-width="1920" data-height="1080" data-start="0" data-duration="{dur}" data-fps="30000/1001" data-track-index="1">
    <div class="cue">
      <span class="dot">&#9679;</span>
      <div class="words">
        {word_spans(text)}
      </div>
    </div>
  </div>
  <script src="assets/gsap.min.js"></script>
  <script>
    const tl = gsap.timeline({{ paused:true }});
    tl.to({{}}, {{ duration:{dur} }}, 0); // Law #11 slot anchor

    // Dot first, then word-by-word fade (Law #10 velocity blur, clears on rest).
    tl.to('.dot', {{ opacity:1, duration:0.25, ease:'power2.out' }}, 0.40);
    tl.fromTo('.w', {{ opacity:0, y:8, filter:'blur(6px)' }},
      {{ opacity:1, y:0, filter:'blur(0px)', duration:0.28, ease:'power2.out', stagger:0.09 }}, 0.52);

    // Tail fade — editor trims or lets it breathe out.
    tl.to('#stage', {{ opacity:0, duration:0.7, ease:'power2.inOut' }}, {dur - 0.8});

    window.__timelines = window.__timelines || {{}};
    window.__timelines['main'] = tl;
  </script>
</body>
</html>
"""

def cta_html(name, l1, l2, dur, note):
    return HEAD.format(name=name, note=note) + f"""
  .cue{{position:absolute;left:140px;bottom:280px;}}
  .row{{display:flex;align-items:baseline;gap:26px;}}
  .dot{{color:#e9edf6;font-size:26px;opacity:0;transform:translateY(-3px);
       text-shadow:0 2px 18px rgba(0,0,0,0.72);}}
  .words{{display:flex;flex-wrap:wrap;gap:0 14px;max-width:1500px;}}
  .w{{font-weight:500;font-size:34px;letter-spacing:0.09em;text-transform:uppercase;
     text-shadow:0 2px 18px rgba(0,0,0,0.72);opacity:0;}}
  .l1 .w{{color:#8995b0;font-weight:400;font-size:28px;}}
  .l2 .w{{color:#e9edf6;}}
  .l2{{margin-top:16px;padding-left:52px;}}
</style>
</head>
<body data-hf-duration="{dur}">
  <div id="stage" data-composition-id="main" data-width="1920" data-height="1080" data-start="0" data-duration="{dur}" data-fps="30000/1001" data-track-index="1">
    <div class="cue">
      <div class="row l1"><span class="dot">&#9679;</span><div class="words">
        {word_spans(l1)}
      </div></div>
      <div class="row l2"><div class="words">
        {word_spans(l2)}
      </div></div>
    </div>
  </div>
  <script src="assets/gsap.min.js"></script>
  <script>
    const tl = gsap.timeline({{ paused:true }});
    tl.to({{}}, {{ duration:{dur} }}, 0); // Law #11 slot anchor

    tl.to('.dot', {{ opacity:1, duration:0.25, ease:'power2.out' }}, 0.40);
    tl.fromTo('.l1 .w', {{ opacity:0, y:8, filter:'blur(6px)' }},
      {{ opacity:1, y:0, filter:'blur(0px)', duration:0.28, ease:'power2.out', stagger:0.07 }}, 0.52);
    tl.fromTo('.l2 .w', {{ opacity:0, y:8, filter:'blur(6px)' }},
      {{ opacity:1, y:0, filter:'blur(0px)', duration:0.28, ease:'power2.out', stagger:0.09 }}, 1.20);

    tl.to('#stage', {{ opacity:0, duration:0.7, ease:'power2.inOut' }}, {dur - 0.8});

    window.__timelines = window.__timelines || {{}};
    window.__timelines['main'] = tl;
  </script>
</body>
</html>
"""

def chip_html(name, icon, term, definition, dur):
    return HEAD.format(name=name, note=f"Definition chip (surface B, AIDR ref-definition-chip). NEW copy — FLAGGED for Dan voice-gate.") + f"""
  /* Baked glass — backdrop-filter does nothing in an alpha overlay (nothing behind it at
     export). Tinted fill + top specular + 1px rim + lift shadow instead. */
  .chip{{position:absolute;left:140px;bottom:160px;display:flex;align-items:center;gap:22px;
    padding:22px 34px 22px 24px;border-radius:16px;opacity:0;
    background:linear-gradient(180deg, rgba(24,32,48,0.72) 0%, rgba(12,18,30,0.66) 100%);
    border:1px solid rgba(233,237,246,0.16);
    box-shadow:0 12px 40px rgba(0,0,0,0.45), inset 0 1px 0 rgba(255,255,255,0.14);}}
  .ico{{width:52px;height:52px;border-radius:11px;display:flex;align-items:center;justify-content:center;
    background:rgba(233,237,246,0.08);border:1px solid rgba(233,237,246,0.14);
    color:#e9edf6;font-size:26px;}}
  .term{{font-weight:500;font-size:30px;letter-spacing:0.09em;color:{BLOSSOM};
    text-shadow:0 2px 14px rgba(0,0,0,0.5);}}
  .eq{{font-weight:400;font-size:28px;color:#5a6480;margin:0 2px;}}
  .def{{font-weight:400;font-size:28px;letter-spacing:0.02em;color:#e9edf6;
    text-shadow:0 2px 14px rgba(0,0,0,0.5);}}
</style>
</head>
<body data-hf-duration="{dur}">
  <div id="stage" data-composition-id="main" data-width="1920" data-height="1080" data-start="0" data-duration="{dur}" data-fps="30000/1001" data-track-index="1">
    <div class="chip" id="chip">
      <div class="ico">{icon}</div>
      <span class="term">{H.escape(term)}</span>
      <span class="eq">=</span>
      <span class="def">{H.escape(definition)}</span>
    </div>
  </div>
  <script src="assets/gsap.min.js"></script>
  <script>
    const tl = gsap.timeline({{ paused:true }});
    tl.to({{}}, {{ duration:{dur} }}, 0); // Law #11 slot anchor

    tl.fromTo('#chip', {{ opacity:0, y:14, filter:'blur(7px)' }},
      {{ opacity:1, y:0, filter:'blur(0px)', duration:0.5, ease:'power2.out' }}, 0.40);

    tl.to('#stage', {{ opacity:0, duration:0.7, ease:'power2.inOut' }}, {dur - 0.8});

    window.__timelines = window.__timelines || {{}};
    window.__timelines['main'] = tl;
  </script>
</body>
</html>
"""

names = []
for name, text, dot, dur, note in CUES:
    open(os.path.join(OUT, name + ".html"), "w").write(cue_html(name, text, dot, dur, note))
    names.append(name)
name, l1, l2, dur, note = CTA
open(os.path.join(OUT, name + ".html"), "w").write(cta_html(name, l1, l2, dur, note))
names.append(name)
for name, icon, term, definition, dur in CHIPS:
    open(os.path.join(OUT, name + ".html"), "w").write(chip_html(name, icon, term, definition, dur))
    names.append(name)
print("\n".join(names))
